PACKAGE_NAME="vivobook-cam-fix"
PACKAGE_VERSION="2.0"
BUILT_MODULE_NAME[0]="vivobook_cam_fix"
DEST_MODULE_LOCATION[0]="/extra"
AUTOINSTALL="yes"
PRE_BUILD="make vivobook_cam_phase1.dtbo.h vivobook_cam_phase2.dtbo.h"
